site_url: https://localhost:8000
repo_url: https://github.com/keithdadkins/beneficiary-fhir-data
repo_name: beneficiary-fhir-data
site_name: 'BFD'
docs_dir: ../../../docs
site_dir: .docs
extra_css:
  - assets/mkdocs.css
theme:
  name: material
  # logo: assets/logo.svg
  locale: en
  font:
    code:
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    # - navigation.top
    - header.autohide
    - navigation.tracking
    # - navigation.tabs
  palette:
    - scheme: lightmode
      primary: light blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # - scheme: darkmode
    #   primary: dark blue
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
markdown_extensions:
  - toc:
      baselevel: 1
      title: On this page
      permalink: True
      toc_depth: 3
  - meta
  - abbr
  - tables
  - attr_list
  - admonition
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
plugins:
  - tags:
        tags_file: tags/index.md
  - search:
      lang: en
  - offline