package gov.cms.bfd.pipeline.rda.grpc.server;

import static junit.framework.TestCase.assertEquals;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import gov.cms.mpsm.rda.v1.mcs.McsClaim;
import gov.cms.mpsm.rda.v1.mcs.McsDiagnosisCode;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.Test;

public class RandomMcsClaimGeneratorTest {
  @Test
  public void randomClaim() throws InvalidProtocolBufferException {
    final Clock july1 = Clock.fixed(Instant.ofEpochMilli(1625172944844L), ZoneOffset.UTC);
    final RandomMcsClaimGenerator generator = new RandomMcsClaimGenerator(1, true, july1);
    final McsClaim claim = generator.randomClaim();
    final String json = JsonFormat.printer().print(claim);
    assertEquals(claim.getIdrDtlCnt(), claim.getMcsDetailsList().size());
    for (McsDiagnosisCode diagnosisCode : claim.getMcsDiagnosisCodesList()) {
      assertEquals(claim.getIdrClmHdIcn(), diagnosisCode.getIdrClmHdIcn());
    }
    assertEquals(
        "{\n"
            + "  \"idrClmHdIcn\": \"484350048435\",\n"
            + "  \"idrContrId\": \"370\",\n"
            + "  \"idrHic\": \"000084555799\",\n"
            + "  \"idrClaimTypeEnum\": \"CLAIM_TYPE_MEDICAL\",\n"
            + "  \"idrDtlCnt\": 3,\n"
            + "  \"idrBeneLast16\": \"hgcbw\",\n"
            + "  \"idrBeneFirstInit\": \"p\",\n"
            + "  \"idrBeneMidInit\": \"m\",\n"
            + "  \"idrStatusCodeEnum\": \"STATUS_CODE_APPROVED_AND_PAID_D\",\n"
            + "  \"idrStatusDate\": \"2021-06-22\",\n"
            + "  \"idrBillProvNpi\": \"5\",\n"
            + "  \"idrBillProvNum\": \"61888\",\n"
            + "  \"idrBillProvEin\": \"jd5\",\n"
            + "  \"idrBillProvType\": \"sz\",\n"
            + "  \"idrBillProvSpec\": \"z\",\n"
            + "  \"idrBillProvPriceSpec\": \"p9\",\n"
            + "  \"idrBillProvCounty\": \"7q\",\n"
            + "  \"idrBillProvLoc\": \"c\",\n"
            + "  \"idrTotAllowed\": \"56.07\",\n"
            + "  \"idrCoinsurance\": \"3.32\",\n"
            + "  \"idrDeductible\": \"93.96\",\n"
            + "  \"idrBillProvStatusCdEnum\": \"BILLING_PROVIDER_STATUS_CODE_NON_PARTICIPATING\",\n"
            + "  \"idrTotBilledAmt\": \"1.75\",\n"
            + "  \"idrClaimReceiptDate\": \"2021-03-23\",\n"
            + "  \"idrClaimMbi\": \"0000084555799\",\n"
            + "  \"mcsDiagnosisCodes\": [{\n"
            + "    \"idrClmHdIcn\": \"484350048435\",\n"
            + "    \"idrDiagIcdTypeEnum\": \"DIAGNOSIS_ICD_TYPE_ICD9\",\n"
            + "    \"idrDiagCode\": \"6kk\"\n"
            + "  }, {\n"
            + "    \"idrClmHdIcn\": \"484350048435\",\n"
            + "    \"idrDiagCode\": \"24\",\n"
            + "    \"idrDiagIcdTypeUnrecognized\": \"x\"\n"
            + "  }],\n"
            + "  \"mcsDetails\": [{\n"
            + "    \"idrDtlFromDate\": \"2021-02-08\",\n"
            + "    \"idrDtlToDate\": \"2021-04-20\",\n"
            + "    \"idrProcCode\": \"4tt\",\n"
            + "    \"idrModOne\": \"0\",\n"
            + "    \"idrModTwo\": \"p\",\n"
            + "    \"idrModThree\": \"pf\",\n"
            + "    \"idrModFour\": \"k\",\n"
            + "    \"idrDtlPrimaryDiagCode\": \"msg1m\",\n"
            + "    \"idrKPosLnameOrg\": \"qggvvsskfwbxgkjcndfzpjjmpphjhpc\",\n"
            + "    \"idrKPosFname\": \"rxxdtdhzqcmbgjzxbnbkfhbwrgbjjdr\",\n"
            + "    \"idrKPosMname\": \"gvhgdjqqqt\",\n"
            + "    \"idrKPosAddr1\": \"4nnnq706bbxz2s\",\n"
            + "    \"idrKPosAddr21st\": \"m14px5zg\",\n"
            + "    \"idrKPosAddr22nd\": \"g85c\",\n"
            + "    \"idrKPosCity\": \"wphbnjzzmrsff\",\n"
            + "    \"idrKPosState\": \"tg\",\n"
            + "    \"idrKPosZip\": \"934003261159817\",\n"
            + "    \"idrDtlDiagIcdTypeUnrecognized\": \"j\",\n"
            + "    \"idrDtlStatusUnrecognized\": \"h\",\n"
            + "    \"idrTosEnum\": \"TYPE_OF_SERVICE_ASSISTANCE_AT_SURGERY\",\n"
            + "    \"idrTwoDigitPosUnrecognized\": \"g1\",\n"
            + "    \"idrDtlRendType\": \"39\",\n"
            + "    \"idrDtlRendSpec\": \"tf\",\n"
            + "    \"idrDtlRendNpi\": \"8\",\n"
            + "    \"idrDtlRendProv\": \"4v7njdf\",\n"
            + "    \"idrKDtlFacProvNpi\": \"tt5hq678\",\n"
            + "    \"idrDtlAmbPickupAddres1\": \"79\",\n"
            + "    \"idrDtlAmbPickupAddres2\": \"20qkrpj787q\",\n"
            + "    \"idrDtlAmbPickupCity\": \"gc2w030hphj5rzf479\",\n"
            + "    \"idrDtlAmbPickupState\": \"b7\",\n"
            + "    \"idrDtlAmbPickupZipcode\": \"mkp5zh\",\n"
            + "    \"idrDtlAmbDropoffName\": \"5t42b8smzn0nknb5k\",\n"
            + "    \"idrDtlAmbDropoffAddrL1\": \"sjbdbtzjck8\",\n"
            + "    \"idrDtlAmbDropoffAddrL2\": \"x16pxzwd59q3sns\",\n"
            + "    \"idrDtlAmbDropoffCity\": \"qs7705gd0cs82bw2f24\",\n"
            + "    \"idrDtlAmbDropoffState\": \"dg\",\n"
            + "    \"idrDtlAmbDropoffZipcode\": \"9j9mk\"\n"
            + "  }, {\n"
            + "    \"idrDtlFromDate\": \"2021-01-28\",\n"
            + "    \"idrDtlToDate\": \"2021-05-03\",\n"
            + "    \"idrProcCode\": \"1mwjm\",\n"
            + "    \"idrModOne\": \"s\",\n"
            + "    \"idrModTwo\": \"4\",\n"
            + "    \"idrModThree\": \"4s\",\n"
            + "    \"idrModFour\": \"t\",\n"
            + "    \"idrDtlDiagIcdTypeEnum\": \"DIAGNOSIS_ICD_TYPE_ICD9\",\n"
            + "    \"idrDtlPrimaryDiagCode\": \"rfpq5z\",\n"
            + "    \"idrKPosLnameOrg\": \"vjchbpvggh\",\n"
            + "    \"idrKPosFname\": \"pdcttnqzbpqrmjgwsqhcqhhjjsbhnb\",\n"
            + "    \"idrKPosMname\": \"wdqndjhpmzvmt\",\n"
            + "    \"idrKPosAddr1\": \"cx27xx1r8fxsv92xjqsh4www6v2\",\n"
            + "    \"idrKPosAddr21st\": \"g5j7g0kp\",\n"
            + "    \"idrKPosAddr22nd\": \"d4\",\n"
            + "    \"idrKPosCity\": \"dgpwwmtfhxsgqtpmqfc\",\n"
            + "    \"idrKPosState\": \"r\",\n"
            + "    \"idrKPosZip\": \"246044958\",\n"
            + "    \"idrDtlStatusUnrecognized\": \"n\",\n"
            + "    \"idrTosEnum\": \"TYPE_OF_SERVICE_HOSPICE\",\n"
            + "    \"idrTwoDigitPosEnum\": \"TWO_DIGIT_PLAN_OF_SERVICE_OFF_CAMPUS_OUTPATIENT_HOSPITAL\",\n"
            + "    \"idrDtlRendType\": \"s\",\n"
            + "    \"idrDtlRendSpec\": \"q5\",\n"
            + "    \"idrDtlRendNpi\": \"xd\",\n"
            + "    \"idrDtlRendProv\": \"202gjq0m53\",\n"
            + "    \"idrKDtlFacProvNpi\": \"t1xfp34wf\",\n"
            + "    \"idrDtlAmbPickupAddres1\": \"8krbjjt1pqg58n\",\n"
            + "    \"idrDtlAmbPickupAddres2\": \"59m\",\n"
            + "    \"idrDtlAmbPickupCity\": \"rvh25f2sb\",\n"
            + "    \"idrDtlAmbPickupState\": \"tm\",\n"
            + "    \"idrDtlAmbPickupZipcode\": \"d1sh\",\n"
            + "    \"idrDtlAmbDropoffName\": \"8b\",\n"
            + "    \"idrDtlAmbDropoffAddrL1\": \"5xdf3twwsmdtfkwqr1jvz7\",\n"
            + "    \"idrDtlAmbDropoffAddrL2\": \"jpxm9jsz\",\n"
            + "    \"idrDtlAmbDropoffCity\": \"j8361bwvjd\",\n"
            + "    \"idrDtlAmbDropoffState\": \"0\",\n"
            + "    \"idrDtlAmbDropoffZipcode\": \"1djtx89p\"\n"
            + "  }, {\n"
            + "    \"idrDtlFromDate\": \"2021-02-13\",\n"
            + "    \"idrDtlToDate\": \"2021-04-10\",\n"
            + "    \"idrProcCode\": \"dd7b\",\n"
            + "    \"idrModOne\": \"vt\",\n"
            + "    \"idrModTwo\": \"3p\",\n"
            + "    \"idrModThree\": \"n\",\n"
            + "    \"idrModFour\": \"5\",\n"
            + "    \"idrDtlDiagIcdTypeEnum\": \"DIAGNOSIS_ICD_TYPE_ICD9\",\n"
            + "    \"idrDtlPrimaryDiagCode\": \"b\",\n"
            + "    \"idrKPosLnameOrg\": \"qksnjwxmgrrxpzzfsshnbgwqs\",\n"
            + "    \"idrKPosFname\": \"vzdnzhhhwtwrmhhpkqmwpvhcvthsrhxc\",\n"
            + "    \"idrKPosMname\": \"zgmqxncdsfvnqwhm\",\n"
            + "    \"idrKPosAddr1\": \"5xb6xp1c0jcb4cxm7wwxhcszqwqg9\",\n"
            + "    \"idrKPosAddr21st\": \"ph88b76\",\n"
            + "    \"idrKPosAddr22nd\": \"xhv09s4mqf6n2k31b0\",\n"
            + "    \"idrKPosCity\": \"vvvjsxsjtdgbhmzszmj\",\n"
            + "    \"idrKPosState\": \"rs\",\n"
            + "    \"idrKPosZip\": \"833\",\n"
            + "    \"idrDtlStatusUnrecognized\": \"j\",\n"
            + "    \"idrTosEnum\": \"TYPE_OF_SERVICE_KIDNEY_DONOR\",\n"
            + "    \"idrTwoDigitPosUnrecognized\": \"f\",\n"
            + "    \"idrDtlRendType\": \"mg\",\n"
            + "    \"idrDtlRendSpec\": \"x\",\n"
            + "    \"idrDtlRendNpi\": \"5jcd\",\n"
            + "    \"idrDtlRendProv\": \"szrr\",\n"
            + "    \"idrKDtlFacProvNpi\": \"khn\",\n"
            + "    \"idrDtlAmbPickupAddres1\": \"301rcr49ns0mqgw2cb4zzj6\",\n"
            + "    \"idrDtlAmbPickupAddres2\": \"cn4k5h\",\n"
            + "    \"idrDtlAmbPickupCity\": \"b52z3p1zhkkc6\",\n"
            + "    \"idrDtlAmbPickupState\": \"jf\",\n"
            + "    \"idrDtlAmbPickupZipcode\": \"03\",\n"
            + "    \"idrDtlAmbDropoffName\": \"r5bp8\",\n"
            + "    \"idrDtlAmbDropoffAddrL1\": \"tjvbrpgt4v2\",\n"
            + "    \"idrDtlAmbDropoffAddrL2\": \"xdsmn3n\",\n"
            + "    \"idrDtlAmbDropoffCity\": \"21zg325\",\n"
            + "    \"idrDtlAmbDropoffState\": \"3\",\n"
            + "    \"idrDtlAmbDropoffZipcode\": \"h6zms\"\n"
            + "  }],\n"
            + "  \"idrBeneSexUnrecognized\": \"p\",\n"
            + "  \"idrBillProvGroupIndUnrecognized\": \"w\",\n"
            + "  \"idrHdrFromDos\": \"2021-01-28\",\n"
            + "  \"idrHdrToDos\": \"2021-05-03\",\n"
            + "  \"idrAssignmentUnrecognized\": \"7\",\n"
            + "  \"idrClmLevelIndUnrecognized\": \"8\",\n"
            + "  \"idrHdrAudit\": 25523,\n"
            + "  \"idrHdrAuditIndEnum\": \"AUDIT_INDICATOR_DETAIL_EDIT_NUMBER\",\n"
            + "  \"idrUSplitReasonUnrecognized\": \"b\",\n"
            + "  \"idrJReferringProvNpi\": \"6k2v3fs2w\",\n"
            + "  \"idrJFacProvNpi\": \"24p5mxp3\",\n"
            + "  \"idrUDemoProvNpi\": \"0bth5s2\",\n"
            + "  \"idrUSuperNpi\": \"gfx1nj\",\n"
            + "  \"idrUFcadjBilNpi\": \"3q6ftzx22\",\n"
            + "  \"idrAmbPickupAddresLine1\": \"6s0g4rqqx9qp24pb3rhw\",\n"
            + "  \"idrAmbPickupAddresLine2\": \"65ttc3cdn\",\n"
            + "  \"idrAmbPickupCity\": \"4\",\n"
            + "  \"idrAmbPickupState\": \"s3\",\n"
            + "  \"idrAmbPickupZipcode\": \"kjz1h\",\n"
            + "  \"idrAmbDropoffName\": \"c8hrc5p\",\n"
            + "  \"idrAmbDropoffAddrLine1\": \"7khhhn0466frjsg26038pg\",\n"
            + "  \"idrAmbDropoffAddrLine2\": \"m3s4wb7qhvqh3\",\n"
            + "  \"idrAmbDropoffCity\": \"96zdpt852\",\n"
            + "  \"idrAmbDropoffState\": \"vr\",\n"
            + "  \"idrAmbDropoffZipcode\": \"9sdtkrmm\",\n"
            + "  \"mcsAudits\": [{\n"
            + "    \"idrJAuditNum\": 13055,\n"
            + "    \"idrJAuditIndUnrecognized\": \"t\",\n"
            + "    \"idrJAuditDispUnrecognized\": \"3\"\n"
            + "  }, {\n"
            + "    \"idrJAuditNum\": 19712,\n"
            + "    \"idrJAuditIndUnrecognized\": \"9\",\n"
            + "    \"idrJAuditDispEnum\": \"CUTBACK_AUDIT_DISPOSITION_AUTO_DENY_WITHOUT_TRANSMIT_TO_CWF\"\n"
            + "  }],\n"
            + "  \"mcsLocations\": [{\n"
            + "    \"idrLocClerk\": \"403q\",\n"
            + "    \"idrLocCode\": \"w2j\",\n"
            + "    \"idrLocDate\": \"2021-04-06\",\n"
            + "    \"idrLocActvCodeUnrecognized\": \"g\"\n"
            + "  }, {\n"
            + "    \"idrLocClerk\": \"q3zh\",\n"
            + "    \"idrLocCode\": \"4z\",\n"
            + "    \"idrLocDate\": \"2021-02-27\",\n"
            + "    \"idrLocActvCodeEnum\": \"LOCATION_ACTIVITY_CODE_CLAIM_IS_MISSING\"\n"
            + "  }, {\n"
            + "    \"idrLocClerk\": \"mw5\",\n"
            + "    \"idrLocCode\": \"t\",\n"
            + "    \"idrLocDate\": \"2021-06-12\",\n"
            + "    \"idrLocActvCodeUnrecognized\": \"g\"\n"
            + "  }, {\n"
            + "    \"idrLocClerk\": \"t\",\n"
            + "    \"idrLocCode\": \"nbp\",\n"
            + "    \"idrLocDate\": \"2021-03-15\",\n"
            + "    \"idrLocActvCodeUnrecognized\": \"r\"\n"
            + "  }, {\n"
            + "    \"idrLocClerk\": \"jtpc\",\n"
            + "    \"idrLocCode\": \"5\",\n"
            + "    \"idrLocDate\": \"2021-01-29\",\n"
            + "    \"idrLocActvCodeUnrecognized\": \"f\"\n"
            + "  }],\n"
            + "  \"mcsAdjustments\": [{\n"
            + "    \"idrAdjDate\": \"2021-03-18\",\n"
            + "    \"idrXrefIcn\": \"5tsrx\",\n"
            + "    \"idrAdjClerk\": \"06k0\",\n"
            + "    \"idrInitCcn\": \"xrsz5g\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-06-22\",\n"
            + "    \"idrAdjBEombAmt\": \"92.46\",\n"
            + "    \"idrAdjPEombAmt\": \"92959.27\"\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-05-13\",\n"
            + "    \"idrXrefIcn\": \"5fq7\",\n"
            + "    \"idrAdjClerk\": \"8\",\n"
            + "    \"idrInitCcn\": \"csxfrc\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-03-14\",\n"
            + "    \"idrAdjBEombAmt\": \"9774.79\",\n"
            + "    \"idrAdjPEombAmt\": \"4400.03\"\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-04-25\",\n"
            + "    \"idrXrefIcn\": \"88107gzznnx9v5\",\n"
            + "    \"idrAdjClerk\": \"ws5h\",\n"
            + "    \"idrInitCcn\": \"9ffc\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-04-15\",\n"
            + "    \"idrAdjBEombAmt\": \"64823.96\",\n"
            + "    \"idrAdjPEombAmt\": \"0.76\"\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-02-19\",\n"
            + "    \"idrXrefIcn\": \"hc5ft3rk\",\n"
            + "    \"idrAdjClerk\": \"9\",\n"
            + "    \"idrInitCcn\": \"dhftsdx4kt02v1z\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-02-18\",\n"
            + "    \"idrAdjBEombAmt\": \"1249.95\",\n"
            + "    \"idrAdjPEombAmt\": \"614.24\"\n"
            + "  }, {\n"
            + "    \"idrAdjDate\": \"2021-01-31\",\n"
            + "    \"idrXrefIcn\": \"x79m54mr7s\",\n"
            + "    \"idrAdjClerk\": \"6\",\n"
            + "    \"idrInitCcn\": \"56gg184r764zdhn\",\n"
            + "    \"idrAdjChkWrtDt\": \"2021-02-18\",\n"
            + "    \"idrAdjBEombAmt\": \"61.58\",\n"
            + "    \"idrAdjPEombAmt\": \"232.81\"\n"
            + "  }]\n"
            + "}",
        json);
  }
}
