package gov.cms.bfd.pipeline.rda.grpc.server;

import static junit.framework.TestCase.assertEquals;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import gov.cms.mpsm.rda.v1.fiss.FissClaim;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.Test;

public class RandomFissClaimGeneratorTest {
  @Test
  public void randomClaim() throws InvalidProtocolBufferException {
    final Clock july1 = Clock.fixed(Instant.ofEpochMilli(1625172944844L), ZoneOffset.UTC);
    final RandomFissClaimGenerator generator = new RandomFissClaimGenerator(1, true, july1);
    final FissClaim claim = generator.randomClaim();
    final String json = JsonFormat.printer().print(claim);
    assertEquals(
        "{\n"
            + "  \"dcn\": \"98455579000000000004843\",\n"
            + "  \"hicNo\": \"000098455579\",\n"
            + "  \"currStatusEnum\": \"CLAIM_STATUS_ROUTING\",\n"
            + "  \"currLoc2Enum\": \"CURRENT_LOCATION_2_POST_PAY_7512\",\n"
            + "  \"totalChargeAmount\": \"1.56\",\n"
            + "  \"recdDtCymd\": \"2021-02-11\",\n"
            + "  \"currTranDtCymd\": \"2021-03-26\",\n"
            + "  \"admDiagCode\": \"nzpggm\",\n"
            + "  \"principleDiag\": \"mxcx\",\n"
            + "  \"npiNumber\": \"4767690551\",\n"
            + "  \"mbi\": \"0000098455579\",\n"
            + "  \"fedTaxNb\": \"7497956907\",\n"
            + "  \"fissProcCodes\": [{\n"
            + "    \"procCd\": \"mxcx\",\n"
            + "    \"procFlag\": \"c\",\n"
            + "    \"procDt\": \"2021-01-10\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"cwdbb\",\n"
            + "    \"procFlag\": \"g\",\n"
            + "    \"procDt\": \"2021-01-03\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"spv\",\n"
            + "    \"procFlag\": \"fs\",\n"
            + "    \"procDt\": \"2021-01-08\"\n"
            + "  }, {\n"
            + "    \"procCd\": \"f\",\n"
            + "    \"procFlag\": \"wk\",\n"
            + "    \"procDt\": \"2021-02-17\"\n"
            + "  }],\n"
            + "  \"medaProvId\": \"gmzw9c6vcs2xq\",\n"
            + "  \"pracLocAddr1\": \"ssv462x9vxmpjb3b\",\n"
            + "  \"pracLocAddr2\": \"fz5qbm7h08g\",\n"
            + "  \"pracLocCity\": \"sb9b66k2v3fs2wf24p5mxp3k0bth5s2vg\",\n"
            + "  \"pracLocState\": \"tq\",\n"
            + "  \"pracLocZip\": \"7992341\",\n"
            + "  \"fissDiagCodes\": [{\n"
            + "    \"diagCd2\": \"qnwggjp\",\n"
            + "    \"bitFlags\": \"c\",\n"
            + "    \"diagPoaIndUnrecognized\": \"d\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"jsnh\",\n"
            + "    \"bitFlags\": \"qc\",\n"
            + "    \"diagPoaIndUnrecognized\": \"b\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"qkmgqms\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_UNREPORTED\",\n"
            + "    \"bitFlags\": \"kdh\"\n"
            + "  }, {\n"
            + "    \"diagCd2\": \"xm\",\n"
            + "    \"diagPoaIndEnum\": \"DIAGNOSIS_PRESENT_ON_ADMISSION_INDICATOR_YES\",\n"
            + "    \"bitFlags\": \"bvzt\"\n"
            + "  }],\n"
            + "  \"currLoc1Unrecognized\": \"r\",\n"
            + "  \"stmtCovFromCymd\": \"2021-02-12\",\n"
            + "  \"stmtCovToCymd\": \"2021-05-07\",\n"
            + "  \"lobCdEnum\": \"BILL_FACILITY_TYPE_RELIGIOUS_NON_MEDICAL_EXTENDED_CARE\",\n"
            + "  \"servTypCdUnrecognized\": \"d\",\n"
            + "  \"freqCdUnrecognized\": \"q\",\n"
            + "  \"billTypCd\": \"qqx\",\n"
            + "  \"fissPayers\": [{\n"
            + "    \"beneZPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_CONDITIONAL_PAYMENT\",\n"
            + "      \"payersName\": \"t6z50nj073j4zjbmbt64\",\n"
            + "      \"relIndUnrecognized\": \"n\",\n"
            + "      \"assignIndUnrecognized\": \"t\",\n"
            + "      \"providerNumber\": \"4mf56kkvfgt24\",\n"
            + "      \"adjDcnIcn\": \"80mpd4ttn0t\",\n"
            + "      \"priorPmt\": \"382.18\",\n"
            + "      \"estAmtDue\": \"5578.10\",\n"
            + "      \"beneRelUnrecognized\": \"82\",\n"
            + "      \"beneLastName\": \"skfwb\",\n"
            + "      \"beneFirstName\": \"gkjcn\",\n"
            + "      \"beneMidInit\": \"f\",\n"
            + "      \"beneSsnHic\": \"kjqnxr52b2rkwhd2f16\",\n"
            + "      \"insuredGroupName\": \"qcmbgjzxbnbkf\",\n"
            + "      \"beneDob\": \"2021-01-31\",\n"
            + "      \"beneSexUnrecognized\": \"r\",\n"
            + "      \"treatAuthCd\": \"b\",\n"
            + "      \"insuredSexEnum\": \"BENEFICIARY_SEX_FEMALE\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_51\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"beneZPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_AUTO_NO_FAULT\",\n"
            + "      \"payersName\": \"xxv5gxnn4nnnq706bbxz2s2\",\n"
            + "      \"relIndUnrecognized\": \"g\",\n"
            + "      \"assignIndEnum\": \"ASSIGNMENT_OF_BENEFITS_INDICATOR_NO_BENEFITS_ASSIGNED\",\n"
            + "      \"providerNumber\": \"zg7g85c7bh1xh\",\n"
            + "      \"adjDcnIcn\": \"dkp1xkrq1nwb6bj92w0g\",\n"
            + "      \"priorPmt\": \"9.17\",\n"
            + "      \"estAmtDue\": \"8275.74\",\n"
            + "      \"beneRelUnrecognized\": \"61\",\n"
            + "      \"beneLastName\": \"xtkfpd\",\n"
            + "      \"beneFirstName\": \"gmmb\",\n"
            + "      \"beneMidInit\": \"v\",\n"
            + "      \"beneSsnHic\": \"678b79220qkrpj787\",\n"
            + "      \"insuredGroupName\": \"mdc\",\n"
            + "      \"beneDob\": \"2021-01-16\",\n"
            + "      \"beneSexEnum\": \"BENEFICIARY_SEX_UNKNOWN\",\n"
            + "      \"treatAuthCd\": \"r\",\n"
            + "      \"insuredSexEnum\": \"BENEFICIARY_SEX_MALE\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_50\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"insuredPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_DISABLED\",\n"
            + "      \"payersName\": \"gqpmkx\",\n"
            + "      \"relIndEnum\": \"RELEASE_OF_INFORMATION_NO_RELEASE_ON_FILE\",\n"
            + "      \"assignIndUnrecognized\": \"d\",\n"
            + "      \"providerNumber\": \"vxrxjwxzdmx\",\n"
            + "      \"adjDcnIcn\": \"rfdgxmvbrqzqbbdwpjwndfx\",\n"
            + "      \"priorPmt\": \"5404.77\",\n"
            + "      \"estAmtDue\": \"99.94\",\n"
            + "      \"insuredRelEnum\": \"PATIENT_RELATIONSHIP_CODE_STEP_CHILD\",\n"
            + "      \"insuredName\": \"cxcjdpcgwzfskwqjpj\",\n"
            + "      \"insuredSsnHic\": \"rhhmnmtccsndjqfjt\",\n"
            + "      \"insuredGroupName\": \"jsdqzgjx\",\n"
            + "      \"insuredGroupNbr\": \"rbstzvjchbpvgg\",\n"
            + "      \"treatAuthCd\": \"0\",\n"
            + "      \"insuredSexUnrecognized\": \"c\",\n"
            + "      \"insuredRelX12Unrecognized\": \"67\",\n"
            + "      \"insuredDob\": \"2021-02-18\",\n"
            + "      \"insuredDobText\": \"02182021\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"beneZPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_OTHER\",\n"
            + "      \"payersName\": \"pg2\",\n"
            + "      \"relIndUnrecognized\": \"q\",\n"
            + "      \"assignIndUnrecognized\": \"q\",\n"
            + "      \"providerNumber\": \"8m6vsfpf\",\n"
            + "      \"adjDcnIcn\": \"83\",\n"
            + "      \"priorPmt\": \"2090.24\",\n"
            + "      \"estAmtDue\": \"294.44\",\n"
            + "      \"beneRelUnrecognized\": \"00\",\n"
            + "      \"beneLastName\": \"cww\",\n"
            + "      \"beneFirstName\": \"pprm\",\n"
            + "      \"beneMidInit\": \"b\",\n"
            + "      \"beneSsnHic\": \"www6v\",\n"
            + "      \"insuredGroupName\": \"xbtnkjkhmjtk\",\n"
            + "      \"beneDob\": \"2021-05-14\",\n"
            + "      \"beneSexEnum\": \"BENEFICIARY_SEX_FEMALE\",\n"
            + "      \"treatAuthCd\": \"w\",\n"
            + "      \"insuredSexEnum\": \"BENEFICIARY_SEX_MALE\",\n"
            + "      \"insuredRelX12Enum\": \"PATIENT_RELATIONSHIP_CODE_RESERVED_FOR_NATIONAL_ASSIGNMENT_84\"\n"
            + "    }\n"
            + "  }, {\n"
            + "    \"insuredPayer\": {\n"
            + "      \"payersIdEnum\": \"PAYERS_CODE_OTHER\",\n"
            + "      \"payersName\": \"qtp\",\n"
            + "      \"relIndUnrecognized\": \"f\",\n"
            + "      \"assignIndUnrecognized\": \"r\",\n"
            + "      \"providerNumber\": \"zmkbpdbtmb\",\n"
            + "      \"adjDcnIcn\": \"bvjqsmsgrzsmdmzwrzmvqpm\",\n"
            + "      \"priorPmt\": \"30.16\",\n"
            + "      \"estAmtDue\": \"2816.02\",\n"
            + "      \"insuredRelUnrecognized\": \"56\",\n"
            + "      \"insuredName\": \"brhsgcrwrxpnhbgbjzsfgvb\",\n"
            + "      \"insuredSsnHic\": \"tdwxjwzzmpjbf\",\n"
            + "      \"insuredGroupName\": \"zzgwn\",\n"
            + "      \"insuredGroupNbr\": \"hwrchbkddjksnt\",\n"
            + "      \"treatAuthCd\": \"j8361bwvjdw0f1djtx\",\n"
            + "      \"insuredSexUnrecognized\": \"g\",\n"
            + "      \"insuredRelX12Unrecognized\": \"43\",\n"
            + "      \"insuredDob\": \"2021-02-13\",\n"
            + "      \"insuredDobText\": \"02132021\"\n"
            + "    }\n"
            + "  }],\n"
            + "  \"fissAuditTrail\": [{\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_SUSPEND\",\n"
            + "    \"badtLoc\": \"b\",\n"
            + "    \"badtOperId\": \"vtb\",\n"
            + "    \"badtReas\": \"p2np5\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-28\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_FORCE\",\n"
            + "    \"badtLoc\": \"t\",\n"
            + "    \"badtOperId\": \"0\",\n"
            + "    \"badtReas\": \"k1b\",\n"
            + "    \"badtCurrDateCymd\": \"2021-04-10\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"k\",\n"
            + "    \"badtLoc\": \"5pz\",\n"
            + "    \"badtOperId\": \"scrrd\",\n"
            + "    \"badtReas\": \"c\",\n"
            + "    \"badtCurrDateCymd\": \"2021-04-22\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"f\",\n"
            + "    \"badtLoc\": \"w6s\",\n"
            + "    \"badtOperId\": \"9f83\",\n"
            + "    \"badtReas\": \"0\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-14\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"n\",\n"
            + "    \"badtLoc\": \"fx\",\n"
            + "    \"badtOperId\": \"3hhzk9g\",\n"
            + "    \"badtReas\": \"84540\",\n"
            + "    \"badtCurrDateCymd\": \"2021-04-22\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_FORCE\",\n"
            + "    \"badtLoc\": \"d7\",\n"
            + "    \"badtOperId\": \"1r5jk\",\n"
            + "    \"badtReas\": \"c9\",\n"
            + "    \"badtCurrDateCymd\": \"2021-03-03\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_INACTIVE\",\n"
            + "    \"badtLoc\": \"x\",\n"
            + "    \"badtOperId\": \"6xp\",\n"
            + "    \"badtReas\": \"c0\",\n"
            + "    \"badtCurrDateCymd\": \"2021-02-28\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"4\",\n"
            + "    \"badtLoc\": \"xm7w\",\n"
            + "    \"badtOperId\": \"x\",\n"
            + "    \"badtReas\": \"csz\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-02\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"g\",\n"
            + "    \"badtLoc\": \"wph88\",\n"
            + "    \"badtOperId\": \"761x\",\n"
            + "    \"badtReas\": \"v0\",\n"
            + "    \"badtCurrDateCymd\": \"2021-02-17\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"m\",\n"
            + "    \"badtLoc\": \"f6n2k\",\n"
            + "    \"badtOperId\": \"1b0dq9hh\",\n"
            + "    \"badtReas\": \"qtph\",\n"
            + "    \"badtCurrDateCymd\": \"2021-02-22\"\n"
            + "  }, {\n"
            + "    \"badtStatusUnrecognized\": \"z\",\n"
            + "    \"badtLoc\": \"4x5ks\",\n"
            + "    \"badtOperId\": \"p7\",\n"
            + "    \"badtReas\": \"96c\",\n"
            + "    \"badtCurrDateCymd\": \"2021-02-14\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_REJECT\",\n"
            + "    \"badtLoc\": \"fhmg\",\n"
            + "    \"badtOperId\": \"x45jcdt\",\n"
            + "    \"badtReas\": \"zr\",\n"
            + "    \"badtCurrDateCymd\": \"2021-05-04\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_DENIED\",\n"
            + "    \"badtLoc\": \"n930\",\n"
            + "    \"badtOperId\": \"rcr49\",\n"
            + "    \"badtReas\": \"s\",\n"
            + "    \"badtCurrDateCymd\": \"2021-06-13\"\n"
            + "  }, {\n"
            + "    \"badtStatusEnum\": \"CLAIM_STATUS_BLANK\",\n"
            + "    \"badtLoc\": \"w2cb4\",\n"
            + "    \"badtOperId\": \"zj6\",\n"
            + "    \"badtReas\": \"c\",\n"
            + "    \"badtCurrDateCymd\": \"2021-01-03\"\n"
            + "  }],\n"
            + "  \"rejectCd\": \"qp24p\",\n"
            + "  \"fullPartDenInd\": \"3\",\n"
            + "  \"nonPayInd\": \"hw\",\n"
            + "  \"xrefDcnNbr\": \"65ttc3cdnq42s3tkj\",\n"
            + "  \"adjReqCdEnum\": \"ADJUSTMENT_REQUESTOR_CODE_PEER_REVIEW_ORGANIZATION\",\n"
            + "  \"adjReasCd\": \"gc\",\n"
            + "  \"cancelXrefDcn\": \"hrc5p47khhhn0\",\n"
            + "  \"cancelDateCymd\": \"2021-05-24\",\n"
            + "  \"cancAdjCdUnrecognized\": \"f\",\n"
            + "  \"originalXrefDcn\": \"jsg26038pgrm3s4w\",\n"
            + "  \"paidDtCymd\": \"2021-06-03\",\n"
            + "  \"admDateCymd\": \"2021-01-16\",\n"
            + "  \"admSourceEnum\": \"SOURCE_OF_ADMISSION_TRANSFER_FROM_AMBULATORY_SURGICAL_CENTER\",\n"
            + "  \"primaryPayerCodeEnum\": \"PAYERS_CODE_BLUE_CROSS\",\n"
            + "  \"attendPhysId\": \"3c\",\n"
            + "  \"attendPhysLname\": \"6zd\",\n"
            + "  \"attendPhysFname\": \"t8521vrb9sd\",\n"
            + "  \"attendPhysMint\": \"k\",\n"
            + "  \"attendPhysFlagEnum\": \"PHYSICIAN_FLAG_NO\",\n"
            + "  \"operatingPhysId\": \"3q85tsrxk06k\",\n"
            + "  \"operPhysLname\": \"6xrsz5gm0xt\",\n"
            + "  \"operPhysFname\": \"m1fhkgs7130q55p5fq\",\n"
            + "  \"operPhysMint\": \"s\",\n"
            + "  \"operPhysFlagEnum\": \"PHYSICIAN_FLAG_NO\",\n"
            + "  \"othPhysId\": \"s\",\n"
            + "  \"othPhysLname\": \"frcghqk\",\n"
            + "  \"othPhysFname\": \"0\",\n"
            + "  \"othPhysMint\": \"r\",\n"
            + "  \"othPhysFlagEnum\": \"PHYSICIAN_FLAG_NO\",\n"
            + "  \"xrefHicNbr\": \"gh4d4tf7h18\",\n"
            + "  \"procNewHicIndEnum\": \"PROCESS_NEW_HIC_INDICATOR_S\",\n"
            + "  \"newHic\": \"7gzznnx\",\n"
            + "  \"reposIndEnum\": \"REPOSITORY_INDICATOR_HIC_HAS_BEEN_MOVED\",\n"
            + "  \"reposHic\": \"vws5h69\",\n"
            + "  \"mbiSubmBeneIndUnrecognized\": \"c\",\n"
            + "  \"adjMbiIndUnrecognized\": \"w\",\n"
            + "  \"adjMbi\": \"ghm8\",\n"
            + "  \"medicalRecordNo\": \"j\"\n"
            + "}",
        json);
  }
}
